version: '3.8'

services:
  usermanagementservice:
    build:
      context: ./userManagementService
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    networks:
      - app-network

  coursemanagmentservice:
    build:
      context: ./courseManagementService
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    networks:
      - app-network

  enrollmentservice:
    build:
      context: ./enrollmentService
      dockerfile: Dockerfile
    ports:
      - "8083:8080"
    networks:
      - app-network

  contentdeliveryservice:
    build:
      context: ./contentDeliveryService
      dockerfile: Dockerfile
    ports:
      - "8084:8080"
    networks:
      - app-network

  quizassignmentservice:
    build:
      context: ./quizAssignmentService
      dockerfile: Dockerfile
    ports:
      - "8085:8080"
    networks:
      - app-network

  progresstrackingservice:
    build:
      context: ./progressTrackingService
      dockerfile: Dockerfile
    ports:
      - "8086:8080"
    networks:
      - app-network

  discussionforumservice:
    build:
      context: ./discussionForumService
      dockerfile: Dockerfile
    ports:
      - "8087:8080"
    networks:
      - app-network

  notificationservice:
    build:
      context: ./notificationService
      dockerfile: Dockerfile
    ports:
      - "8088:8080"
    networks:
      - app-network

  billingpaymentservice:
    build:
      context: ./billingPaymentService
      dockerfile: Dockerfile
    ports:
      - "8089:8080"
    networks:
      - app-network

  reportinganalyticsservice:
    build:
      context: ./reportingAnalyticsService
      dockerfile: Dockerfile
    ports:
      - "8090:8080"
    networks:
      - app-network

  adminmanagmentservice:
    build:
      context: ./adminManagementService
      dockerfile: Dockerfile
    ports:
      - "8091:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
