spring:
  datasource:
    url: jdbc:postgresql://ep-restless-waterfall-a2y59272.eu-central-1.aws.neon.tech/courseManagement
    username: courseManagement_owner
    password: v5nCxNmWLR7q
    driver-class-name: org.postgresql.Driver
  application:
    name: courseManagementService
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true