
server:
  port: 8222

spring:
  datasource:
    url: jdbc:postgresql://ep-noisy-truth-a8tqg0go.eastus2.azure.neon.tech/userManagement
    username: userManagement_owner
    password: YPBSExVb04Ay
    driver-class-name: org.postgresql.Driver
  application:
    name: gatewayService
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
