
server:
  port: 8222

spring:
  datasource:
    url: jdbc:sqlserver://lms19.database.windows.net:1433;database=user_management_db;
    username: CloudSA96eccfc5@lms19
    password: Nozom@2020
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  application:
    name: gatewayService
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
