server:
  port: 8222

spring:
  datasource:
    url: jdbc:sqlserver://lms19.database.windows.net:1433;database=user_management_db;
    username: CloudSA96eccfc5@lms19
    password: Nozom@2020
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    gateway:
        routes:
          - id: reportingAnalyticsService
            uri: lb:http://REPORTINGANALYTICSSERVICE
            predicates:
              - Path=/reportingAnalytics/**
          - id: userManagementService
            uri: lb:http://USERMANAGEMENTSERVICE
            predicates:
              - Path=/user/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true