server:
  port: 8222
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: reportingAnalyticsService
          uri: lb:http://REPORTINGANALYTICSSERVICE
          predicates:
            - Path=/reportingAnalytics/**
