server:
  port: 8222
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: reportingAnalytics
          uri: lb:http://CUSTOMER-SERVICE
          predicates:
            - Path=/reportingAnalytics/**